// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"
import uuid "github.com/satori/go.uuid"

// UUIDInterface is an autogenerated mock type for the UUIDInterface type
type UUIDInterface struct {
	mock.Mock
}

// GenerateState provides a mock function with given fields:
func (_m *UUIDInterface) GenerateState() (string, error) {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewV4 provides a mock function with given fields:
func (_m *UUIDInterface) NewV4() (uuid.UUID, error) {
	ret := _m.Called()

	var r0 uuid.UUID
	if rf, ok := ret.Get(0).(func() uuid.UUID); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
